docsPath: myapp-docs
structure:
  summary: toc.md
  assets: assets
# This will include all code files from your repo
docTreeOptions:
    showDownloadOpenApiFile: true
    shouldCreateSchemaCategory: true
