docsPath: myapp-docs
docsPath: folderZ
structure:
  summary: toc.md
  assets: assets
# This will include all code files from your repo
docTreeOptions:
    showDownloadOpenApiFile: true
    shouldCreateSchemaCategory: true
shadowDocs: 
  - "*"
  - "ola.json"

